### ISSUE TITLE
Unite 2018 - Visual Effect Graph - Finally released, walk through Help!!!

### ISSUE THREAD

**Issue by BlissettDMB** [peeweek/VisualEffectGraph-EasySetup#1]
I've done a download, and have been able to load the sample scene, but where is the original Visual Effect Graph from Unite 2018. 

I got this:
![result001](https://user-images.githubusercontent.com/4721275/47953983-94c9ec00-df7c-11e8-90ea-f714fbf2f044.jpg)

But I'm looking for this:
![result000](https://user-images.githubusercontent.com/4721275/47954001-d195e300-df7c-11e8-9191-e6dd544da016.jpg)

I've done a pull on Git from https://github.com/Unity-Technologies/ScriptableRenderPipeline, placed the packages, and moved the sample scene into the access folder (and deleted the test libraries).

All I get is a blue scene. No animations, cut scenes, geo... nothing.

How do we get to preview the sample that was shown at Unite 2018???? Help :)

**Comment by peeweek** [comment]
The demo from unite is a really big project that will not fit at the moment on a GitHub repo. We are working on cleaning it to release it. But no ETA yet.

Also, This project is not affiliated in any kind to unity. It's only a boilerplate to install packages.
